In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/mricardo89/data-mining/main/Unit-II/datasets/googleplaystore.csv"
df = pd.read_csv(url)

### Pregunta A: 
#### El scraper cometió errores y guardó la misma app varias veces. Escriban una línea de código para identificar si hay nombres duplicados en la columna App (df.duplicated(subset=['App']).sum()). Si los hay, apliquen .drop_duplicates(subset=['App'], keep='first', inplace=True) para quedarse solo con la primera aparición de cada aplicación. 
#### ¿Cuántos registros duplicados purgaron?
##### 1181

In [2]:
print(df.duplicated(subset=['App']).sum())

df.drop_duplicates(subset=['App'], keep='first', inplace=True)

print(df.duplicated(subset=['App']).sum())

1181
0

### Pregunta B: 
#### La columna Installs tiene texto como "1,000,000+". Un algoritmo no puede procesar eso.
#### Escriban una instrucción encadenando el método .str.replace() para eliminar el símbolo + y otro para eliminar la coma ,. (Ojo: utilicen regex=False o escapen el símbolo más \+).
#### Al final de la cadena, utilicen .astype(int) (o float si tienen NaNs) para convertir la columna.
#### Comprueben el éxito ejecutando df['Installs'].mean(). ¿Cuál es el promedio real de descargas?

##### 7.777506 millones de descargas.

In [3]:
df = df[df['Installs'] != 'Free']

df['Installs']=(
    df['Installs'].str.replace('+','',regex=False)
    .str.replace(',','',regex=False).astype(float)
)

print(df['Installs'].mean())

7777506.732270421

### Pregunta C: 
### La columna Price tiene valores como "$4.99" y "0". Apliquen la misma lógica arquitectónica que en la Pregunta B: eliminen el símbolo de dólar y conviertan la columna usando .astype(float).

#### El promedio de los precios es $1.0992990992856404

In [4]:
df['Price']=(
    df['Price'].str.replace('$','',regex=False).astype(float)
)

print(df['Price'].mean())

1.0992990992856404

### Pregunta D: 
#### Ahora que el precio es numérico, ejecuten df['Price'].max(). Notarán que la app más cara cuesta alrededor de 400 dólares.
#### Usen un filtro booleano (df[df['Price'] > 200]) para descubrir cuáles son estas apps. Verán que son aplicaciones basura o de broma.
#### Si metemos estas apps al modelo, la red neuronal creerá que vender a 400 dólares es un modelo de negocio viable. Sobrescriban el DataFrame conservando únicamente las apps que cuesten menos de 50 dólares (df = df[df['Price'] < 50]).
#### Guarden su dataset final usando df.to_csv('playstore_limpio.csv', index=False).

In [5]:
df['Price'].max()

df[df['Price'] > 200]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4197,most expensive app (H),FAMILY,4.3,6,1.5M,100.0,Paid,399.99,Everyone,Entertainment,"July 16, 2018",1.0,7.0 and up
4362,💎 I'm rich,LIFESTYLE,3.8,718,26M,10000.0,Paid,399.99,Everyone,Lifestyle,"March 11, 2018",1.0.0,4.4 and up
4367,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7.3M,10000.0,Paid,400.00,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1 and up
5351,I am rich,LIFESTYLE,3.8,3547,1.8M,100000.0,Paid,399.99,Everyone,Lifestyle,"January 12, 2018",2.0,4.0.3 and up
5354,I am Rich Plus,FAMILY,4.0,856,8.7M,10000.0,Paid,399.99,Everyone,Entertainment,"May 19, 2018",3.0,4.4 and up
5355,I am rich VIP,LIFESTYLE,3.8,411,2.6M,10000.0,Paid,299.99,Everyone,Lifestyle,"July 21, 2018",1.1.1,4.3 and up
5356,I Am Rich Premium,FINANCE,4.1,1867,4.7M,50000.0,Paid,399.99,Everyone,Finance,"November 12, 2017",1.6,4.0 and up
5357,I am extremely Rich,LIFESTYLE,2.9,41,2.9M,1000.0,Paid,379.99,Everyone,Lifestyle,"July 1, 2018",1.0,4.0 and up
5358,I am Rich!,FINANCE,3.8,93,22M,1000.0,Paid,399.99,Everyone,Finance,"December 11, 2017",1.0,4.1 and up
5359,I am rich(premium),FINANCE,3.5,472,965k,5000.0,Paid,399.99,Everyone,Finance,"May 1, 2017",3.4,4.4 and up
5362,I Am Rich Pro,FAMILY,4.4,201,2.7M,5000.0,Paid,399.99,Everyone,Entertainment,"May 30, 2017",1.54,1.6 and up
5364,I am rich (Most expensive app),FINANCE,4.1,129,2.7M,1000.0,Paid,399.99,Teen,Finance,"December 6, 2017",2,4.0.3 and up
5366,I Am Rich,FAMILY,3.6,217,4.9M,10000.0,Paid,389.99,Everyone,Entertainment,"June 22, 2018",1.5,4.2 and up
5369,I am Rich,FINANCE,4.3,180,3.8M,5000.0,Paid,399.99,Everyone,Finance,"March 22, 2018",1.0,4.2 and up
5373,I AM RICH PRO PLUS,FINANCE,4.0,36,41M,1000.0,Paid,399.99,Everyone,Finance,"June 25, 2018",1.0.2,4.1 and up
9917,Eu Sou Rico,FINANCE,NaN,0,1.4M,0.0,Paid,394.99,Everyone,Finance,"July 11, 2018",1.0,4.0.3 and up
9934,I'm Rich/Eu sou Rico/أنا غني/我很有錢,LIFESTYLE,NaN,0,40M,0.0,Paid,399.99,Everyone,Lifestyle,"December 1, 2017",MONEY,4.1 and up

In [6]:
df = df[df['Price'] < 50]

df[df['Price'] > 200]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [7]:
df.to_csv('playstore_limpio.csv',index=False)